### PR TITLE
Add Calendar app and useful doc materials 

### PR DESCRIPTION
**Pull request by tamakarowa**
This PR includes: 
1. SimpleCalendar application with opportunity to plan actions and to watch actions which were planned;
2. Abstract with lines theme;  
3. Doc with with useful links for key, recycle operators and arrays.

### CODE REVIEW

**Comment by MikhailMasny** [comment]
There are two comments..
1. Why you use solution but not project?
2. Dont see enum in your project..

**Comment by tamakarowa** [comment]
> There are two comments..
> 
> 1. Why you use solution but not project?
> 2. Dont see enum in your project..

Thank you for comments!
1. I used a project. src/Calendar/SimpleCalendar/SimpleCalendar/SimpleCalendar.csproj 
2. Is this critical to use enum? I more like to use an array

**Comment by MikhailMasny** [comment]
> > There are two comments..
> > 
> > 1. Why you use solution but not project?
> > 2. Dont see enum in your project..
> 
> Thank you for comments!
> 
> 1. I used a project. src/Calendar/SimpleCalendar/SimpleCalendar/SimpleCalendar.csproj
> 2. Is this critical to use enum? I more like to use an array

1. Yes, but at this way "TMS-DotNet/src/Calendar/SimpleCalendar/" you used *.sln. You need only one *.sln in your repo and this is Makarova.TMS.0201.sln
2. Yes, because we need more practic with it now. You need use and enum, and array.

**Comment by tamakarowa** [comment]
@MikhailMasny got it, please look at the last commit

**Pull request merged**
